motors:
  m1:
    joint: robot_back_left_joint
    can_id: 1
  m2:
    joint: robot_back_right_joint
    can_id: 2
  m3:
    joint: robot_front_left_joint
    can_id: 3
  m4:
    joint: robot_front_right_joint
    can_id: 4
battery_voltage:
  - [27.09, 100]
  - [26.62, 90]
  - [26.52, 80]
  - [26.40, 70]
  - [26.33, 60]
  - [26.26, 50]
  - [26.16, 40]
  - [25.99, 30]
  - [25.78, 20]
  - [25.48, 10]
  - [22.88, 0]

battery_amperes: 15
battery_alarm_voltage: 24.5
num_inputs_per_driver: 5
num_outputs_per_driver: 3
# A/h (to simulate battery discharge)
power_consumption: 2.5
# A/h to simulate the battery charge
power_charge: 10
num_analog_inputs_per_driver: 1
# Values to multiply on IO raw data received
k_analog_inputs_multipliers: [6.978947368, -12.5, 1.0, 1.0]
voltage_analog_input_number: 1
current_analog_input_number: 2
inverted_contact_relay: true
contact_relay_digital_input_number: 2
charge_digital_output_number: 1
